### ISSUE TITLE
Ain't working with java 1.8

### ISSUE THREAD

**Issue by RaniRaven** [amiya-pattnaik/node-any-jdbc#1]
In contradiction to the read me , the npm install insist on using java@0.7.2, could not find any way to change this.
Therefore node-gyp fails.
Can't believe there is not a single jdbc support for node.js around there.
Everything is compiled with java 1.6 or java 1.7

**Comment by amiya-pattnaik** [comment]
Hi RaniRaven,
We have tested this module on several MAC OS as well as Windows with JDK 1.8 and it works.
regarding java@0.7.2, it is node's bridge between your JDK and you should not worried about it and your installed JDK remains unchanged. By the way which OS you are using. If MAC, then make sure you have XCODE. In case of windows, it has some problem in build tools. follow the steps you should be able to install it

**Comment by amiya-pattnaik** [comment]
Hope above solution worked. closing this ticket.
